// Vendors the shared libraries + stylesheet into the web part source folder.
// SheetJS/HyperFormula are copied in as plain side-effect .js files (allowJs
// is enabled in tsconfig.json specifically for this) — webpack bundles them
// like any other module, executing their UMD wrapper the same way a <script>
// tag would, which sets window.XLSX / window.HyperFormula as a side effect.
//
// app.css is embedded as a TS string constant (JSON-stringified, so no
// content can break out of the template) rather than routed through SCSS
// modules, so it can be reused byte-for-byte and injected as a plain <style>
// tag at runtime instead of hand-porting every class into .module.scss.
const fs = require('fs');
const path = require('path');

const SIBLING_DIR = path.join(__dirname, '..', 'browser-converter');
const CORE_DIR = path.join(SIBLING_DIR, 'core');
const VENDOR_DIR = path.join(__dirname, 'src', 'webparts', 'interactivePlan', 'vendor');

fs.mkdirSync(VENDOR_DIR, { recursive: true });

fs.copyFileSync(
  path.join(CORE_DIR, 'xlsx.core.min.js'),
  path.join(VENDOR_DIR, 'xlsx.core.min.js')
);
fs.copyFileSync(
  path.join(CORE_DIR, 'hyperformula.bundle.js'),
  path.join(VENDOR_DIR, 'hyperformula.bundle.js')
);
fs.copyFileSync(
  path.join(CORE_DIR, 'convert-core.js'),
  path.join(VENDOR_DIR, 'convert-core.js')
);
fs.copyFileSync(
  path.join(CORE_DIR, 'render-core.js'),
  path.join(VENDOR_DIR, 'render-core.js')
);

const appCss = fs.readFileSync(path.join(CORE_DIR, 'app.css'), 'utf8');
const tsSource = `// Auto-generated by vendor.js from ../browser-converter/core/app.css — do not edit directly.\nexport const APP_CSS: string = ${JSON.stringify(appCss)};\n`;
fs.writeFileSync(path.join(VENDOR_DIR, 'appStyles.ts'), tsSource);

console.log('Vendored xlsx.core.min.js, hyperformula.bundle.js, convert-core.js, render-core.js, and appStyles.ts into src/webparts/interactivePlan/vendor/');
