// Vendors the shared libraries + stylesheet into the web part source folder.
//
// xlsx.core.min.js / convert-core.js are copied in as plain side-effect .js
// files (allowJs is enabled in tsconfig.json specifically for this) —
// webpack bundles them like any other module, executing them the same way
// a <script> tag would.
//
// hyperformula.bundle.js and render-core.js are NOT copied as plain .js
// files, unlike the two above — confirmed that letting tsc's allowJs
// pipeline recompile the already-built hyperformula.bundle.js (target es5)
// silently breaks its formula evaluator: parsing still works
// (getCellFormula/getCellType report correctly) but getCellValue throws
// "Value of the formula cell is not computed" for every formula, even a
// trivial =A1+B1 in a brand-new engine. Reproduced in complete isolation
// outside of SPFx/webpack, so it's tsc's ES5 downlevel of this particular
// minified bundle at fault, not anything SharePoint-specific.
//
// render-core.js has to move with it: its outer IIFE captures `HyperFormula`
// from `root.HyperFormula` exactly once, at the moment it executes —
// `factory(root.XLSX, root.HyperFormula)`. A static `import` runs at module
// load time, before HyperFormula has been injected, so createEngine would
// close over `undefined`. Both are instead embedded as TS string constants
// (like app.css below) and injected as real <script> tags at runtime, in
// order (HyperFormula first) — see ensureEngineLibsLoaded() in
// InteractivePlanWebPart.ts — so tsc only ever sees them as inert string
// data, never as JS it tries to parse and re-emit. XLSX doesn't need this:
// render-core.js's `root.XLSX` capture is fine since xlsx.core.min.js's
// static import already runs before any class method does.
//
// app.css is embedded as a TS string constant (JSON-stringified, so no
// content can break out of the template) rather than routed through SCSS
// modules, so it can be reused byte-for-byte and injected as a plain <style>
// tag at runtime instead of hand-porting every class into .module.scss.
const fs = require('fs');
const path = require('path');

const SIBLING_DIR = path.join(__dirname, '..', 'browser-converter');
const CORE_DIR = path.join(SIBLING_DIR, 'core');
const VENDOR_DIR = path.join(__dirname, 'src', 'webparts', 'interactivePlan', 'vendor');

fs.mkdirSync(VENDOR_DIR, { recursive: true });

fs.copyFileSync(
  path.join(CORE_DIR, 'xlsx.core.min.js'),
  path.join(VENDOR_DIR, 'xlsx.core.min.js')
);
fs.copyFileSync(
  path.join(CORE_DIR, 'convert-core.js'),
  path.join(VENDOR_DIR, 'convert-core.js')
);

// Remove any stale copies from before hyperformula.bundle.js/render-core.js
// were switched to string-embedding, so a leftover file can't get
// accidentally picked up by anything.
for (const stale of ['hyperformula.bundle.js', 'render-core.js']) {
  const staleFile = path.join(VENDOR_DIR, stale);
  if (fs.existsSync(staleFile)) fs.rmSync(staleFile);
}

function writeSourceConstant(srcFileName, constName, outFileName) {
  const src = fs.readFileSync(path.join(CORE_DIR, srcFileName), 'utf8');
  const ts = `// Auto-generated by vendor.js from ../browser-converter/core/${srcFileName} — do not edit directly.\n// Deliberately a string, not a side-effect JS import — see the comment at the top of vendor.js for why.\nexport const ${constName}: string = ${JSON.stringify(src)};\n`;
  fs.writeFileSync(path.join(VENDOR_DIR, outFileName), ts);
}

writeSourceConstant('hyperformula.bundle.js', 'HYPERFORMULA_SOURCE', 'hyperformulaSource.ts');
writeSourceConstant('render-core.js', 'RENDER_CORE_SOURCE', 'renderCoreSource.ts');

const appCss = fs.readFileSync(path.join(CORE_DIR, 'app.css'), 'utf8');
const tsSource = `// Auto-generated by vendor.js from ../browser-converter/core/app.css — do not edit directly.\nexport const APP_CSS: string = ${JSON.stringify(appCss)};\n`;
fs.writeFileSync(path.join(VENDOR_DIR, 'appStyles.ts'), tsSource);

console.log('Vendored xlsx.core.min.js, convert-core.js, hyperformulaSource.ts, renderCoreSource.ts, and appStyles.ts into src/webparts/interactivePlan/vendor/');
